sudo: false

cache:
  directories:
    - node_modules

language: node_js
node_js:
  - "6"

before_script:
  - "npm i -D"

script:
  - "npm run coverage"

after_script:
  - "cat ./coverage/lcov.info | coveralls"